### ISSUE TITLE
New resource type: codeconnections, codestar-connections

### ISSUE THREAD

**Issue by dleavitt** [link2aws/link2aws.github.io#63]
Info:

* ARN: `arn:aws:codeconnections:us-west-2:123456789012:connection/12345678-90ab-cdef-1234-567890abcdef`
* AWS console URL for above ARN: https://us-west-2.console.aws.amazon.com/codesuite/settings/123456789012/us-west-2/codeconnections/connections/12345678-90ab-cdef-1234-567890abcdef
* Screenshot of AWS console at above URL: (omitted due to paranoia)

There's also a sort of equivalent resource (old version of the same thing, I think) that lives under the codestar-connections resource type. The ARN/URL formula is the same as the above, with `codeconnections` replaced with `codestar-connections`:

* ARN: `arn:aws:codestar-connections:us-west-2:123456789012:connection/12345678-90ab-cdef-1234-567890abcdef`
* AWS console URL for above ARN: https://us-west-2.console.aws.amazon.com/codesuite/settings/123456789012/us-west-2/codestar-connections/connections/12345678-90ab-cdef-1234-567890abcdef

Notes:
- Console URLs for these are especially useful, as they can't be fully created programmatically - there's a step that needs to be done via the console.
- Create one from here: https://us-west-2.console.aws.amazon.com/codesuite/settings/connections
- I'm not sure the codestar ones can be created via the console anymore? Can still be created via API or Cloudformation though.
- Happy to open a PR!

Cloudformation Entities:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codeconnections-connection.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarconnections-connection.html

Some code:
```typescript
const [prefix, id] = arn.split("/");
const [, , ns, region, account] = prefix.split(":");
const url = `https://${region}.console.aws.amazon.com/codesuite/settings/${account}/${region}/${ns}/connections/${id}`;
```

**Comment by fxkr** [comment]
Thanks! That would be a great contribution. Feel free to open a PR, if you like! It looks like it should be a fairly straightforward change (1 line per resource type, + tests), as it seems all the necessary variables are already available.

Otherwise I can do the code change as well, but then it may take me a days to find time.

**Comment by dleavitt** [comment]
Will do
